sudo: required
dist: trusty
language: node_js
node_js:
- stable
branches:
  except:
  - gh-pages
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install web-component-tester
- npm install bower
- export PATH=$PWD/node_modules/.bin:$PATH
- bower install
script:
- xvfb-run wct --skip-plugin sauce
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct --plugin sauce --skip-plugin
  local; fi
after_success:
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then openssl aes-256-cbc -k "$DEPLOYSECRET"
  -in deploy.enc -out deploy_key -d; fi
- cd $TRAVIS_BUILD_DIR/scripts
- chmod 755 ghp.sh
- "./ghp.sh"
env:
  global:
  - secure: ZommiDhwGyzSRbJq38uHaRvxBhk8SQy4pfszlLbK9VK64Kk8E7zSsgITiL/bkVUgescK0M72PIDdTBA+gzTkmTDAU3ka/7jXzRafsWdNsyCHG1+NO9i5lJX1Y342X/RGMHwjULRlNXQ0pw15j5p3t1O2EsMs1ZoSv2Y65FRwqB9pbIbX+ahZwOe0QXGfKo/YoYBALdfXYqzMEzJRjuwqQeZqFv+ZcayTVKiktE/8ti/2TbHJdOOErlkcZWG451ZPKNqm7MyQCVcwvIXQ3q/PADyc/nXumhqDgPPucQFCOH53KopRqSTZN6ThTE0iEPnnxeHTNoQnTTVdrz44TFCi7zcZEN210CAAG+QIQBNJIabR60W4tL1YFVJ0w66gZ/1wBspmrrIxbmfCxYE5cVenNpQbBr462BS89ROQcFWi7CghEW3xRvKbgZ0vLjCH3m8njCfazX+19aPibu2O2SadzkJPoc6j/GlKC4vUMxilGg1WERKq93aMWXe6hejbwegFHW1xB7HGggbR+MU+2UYpLq3fj1QjC740Z51lQ+zRCeZEZvw94rwLWXdnR3aHu8yZTlaDZl7jBJ0zeHboQliKx0SgNIXUDridAZhxOnzQ4kYWbFFuspZtsmnbKXOZkcM+lMP9t0NLX9fHSHr+mnrht88lL5XdFrxZDq62EYd/Y3E=
  - secure: pYIrb3gfkOjD0q7eRLP29aMAC9s4eYKdQRXgz1yc/FWX44lOXFNnjugc9MKCPqi9uoz2QBDm9yLHZbhOccRLsN/Hu1WCGep4LPwGW9a/Fpv7TXmdWmZDf+/u4jq8hB3sUe0emslztemGCrZYc+XiPQREIeFYx4EaN6IdklzNrB3pT8LLqdvvd99YmxXLGYwx3CGayeh+HI/68U2AY709WXHUqQkdQ5mm5RtRfg0eA2gVp/6gYpxs5qsAymhvYB5fTUP0aSH2+VLrVE1R0E6+aaphf884k4NeDwlc6/6E/2+HgHcAWmhPd8dNPh9QkxsjCAOCgOskLWoF2WwSw6Tel2KWUvWpA2tt+wrGA8dRduyXk5VVe4w+TAR36vAgjMPEUy1r5AZoQGzemkVpNXOM/C9BH5fuWy5GOQfVD3YZpk6d1SgBVf2PEvi8Eioy+IvJeLVINgWIDIk30fYjllNEDXav09DgCTp0h1uEXbcGo8dr4YdCVGOdYUQbJaU2FTqNXeKUtXJAnpmX+O25Dti/8x3RyJdrOhIpT+ww08igRsK5Xar0wAJid43Ji8R/mfwe8uweGxegbihAwekK6pqoaBGWG0O8KzbvJJxSiFBqzpWflC2FVBs46zuNoXkptU+GZgi1MGdvhsVvr36iZ7/juwUzi8/SMNKUtB0ptI1hIGc=
